package com.ecommerce.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ExceptionEnum {
    BRAND_NOT_FOUND(404,"BRAND_NOT_FOUND"),
    BRAND_SAVE_ERROR(500,"BRAND_SAVE_ERROR"),
    GOODS_SAVE_ERROR(500,"GOODS_SAVE_ERROR"),
    CATEGORY_NOT_FOUND(404,"CATEGORY_NOT_FOUND"),
    SPEC_GROUP_NOT_FOUND(404,"SPEC_GROUP_NOT_FOUND"),
    SPEC_PARAM_NOT_FOUND(404,"SPEC_PARAM_NOT_FOUND"),
    GOODS_NOT_FOUND(404,"GOODS_NOT_FOUND"),
    GOODS_DETAIL_NOT_FOUND(404,"GOODS_DETAIL_NOT_FOUND"),
    GOODS_SKU_NOT_FOUND(404,"GOODS_SKU_NOT_FOUND"),
    GOODS_STOCK_NOT_FOUND(404,"GOODS_STOCK_NOT_FOUND"),
    UPLOAD_FILE_ERROR(500,"UPLOAD_FILE_ERROR"),
    INVALID_FILE_TYPE(400,"INVALID_FILE_TYPE"),
    GOODS_UPDATE_ERROR(500,"GOODS_UPDATE_ERROR"),
    INVALID_USER_DATA_TYPE(400,"INVALID_USER_DATA_TYPE"),
    VERIFY_CODE_NOT_MATCHING(400,"VERIFY_CODE_NOT_MATCHING"),
    USER_NOT_EXIST(404,"USER_NOT_EXIST"),
    PASSWORD_NOT_MATCHING(400,"PASSWORD_NOT_MATCHING"),
    USERNAME_OR_PASSWORD_ERROR(500, "USERNAME_OR_PASSWORD_ERROR"),
    UNAUTHORIZED(403, "UNAUTHORIZED"),
    CART_NOT_FOUND(404,"CART_NOT_FOUND"),
    RECEIVER_ADDRESS_NOT_FOUND(404,"RECEIVER_ADDRESS_NOT_FOUND"),
    CREATE_ORDER_ERROR(500,"CREATE_ORDER_ERROR"),
    STOCK_NOT_ENOUGH(500,"STOCK_NOT_ENOUGH"),
    ORDER_NOT_FOUND(404,"ORDER_NOT_FOUND"),
    WX_PAY_ORDER_FAIL(500,"WX_PAY_ORDER_FAIL"),
    ORDER_STATUS_EXCEPTION(500,"ORDER_STATUS_EXCEPTION"),
    INVALID_SIGN_ERROR(400,"INVALID_SIGN_ERROR"),
    INVALID_ORDER_PARAM(400,"INVALID_ORDER_PARAM"),
    UPDATE_ORDER_STATUS_ERROR(500,"UPDATE_ORDER_STATUS_ERROR"),
    INIT_KEYS_ERROR(500,"INIT_KEYS_ERROR")
    ;
    private int code;
    private String msg;
}