server:
  port: 10010
spring:
  application:
    name: ecommerce-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order-service/**
  # These two are for reading cookies
  add-host-header: true
  sensitive-headers:
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3500
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000
ly:
  jwt:
    pubKeyPath: D:/tmp/id_rsa.pub
    cookieName: E_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /zuul/api/upload
      - /api/item